import {forwardRef,useEffect,useImperativeHandle,useMemo,useRef,useState} from 'react';
import {View,Text} from 'react-native';
import {IconButton} from './UI';
import {rgb,type Pattern} from '../lib/pattern';
import {type Region,type Viewport} from '../lib/projects';
import {cellAt,clampViewport,fitRegion,zoomAt} from '../lib/viewport';
export type CanvasHandle={fit:(region?:Region)=>void;focusCell:(index:number)=>void};
type Props={pattern:Pattern;completed:number[];region:Region;color:number|null;initialView:Viewport|null;locked:boolean;selected:number|null;onCell:(index:number)=>void;onView:(view:Viewport)=>void;onLock:()=>void};
export const PatternCanvas=forwardRef<CanvasHandle,Props>(function PatternCanvas(props,ref){
 const {pattern,completed,region,color,selected,locked}=props, host=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement>(null);
 const [size,setSize]=useState({width:0,height:0}),[view,setView]=useState(props.initialView??{cx:pattern.width/2,cy:pattern.height/2,scale:10});
 const live=useRef({props,size,view});live.current={props,size,view};const initialized=useRef(false);
 function change(v:Viewport,persist=false){const l=live.current,next=clampViewport(v,l.props.pattern,l.size);live.current.view=next;setView(next);if(persist)l.props.onView(next);}
 useEffect(()=>{const obs=new ResizeObserver(([entry])=>{const {width,height}=entry.contentRect;setSize({width,height});});obs.observe(host.current!);return()=>obs.disconnect();},[]);
 useEffect(()=>{if(!initialized.current&&size.width&&size.height){initialized.current=true;change(props.initialView??fitRegion({x:0,y:0,width:pattern.width,height:pattern.height},size));}},[size]);
 useImperativeHandle(ref,()=>({fit:r=>{if(!locked)change(fitRegion(r??{x:0,y:0,width:pattern.width,height:pattern.height},size),true);},focusCell:i=>{if(!locked)change({cx:i%pattern.width+.5,cy:Math.floor(i/pattern.width)+.5,scale:Math.max(view.scale,32)},true);}}),[locked,size,pattern,view]);
 const done=useMemo(()=>new Set(completed),[completed]);
 const raster=useMemo(()=>{const c=document.createElement('canvas');c.width=pattern.width;c.height=pattern.height;const ctx=c.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);pattern.cells.forEach((n,i)=>{if(n<0)return;ctx.globalAlpha=done.has(i)?1:color!==null&&color!==n?.16:1;ctx.fillStyle=done.has(i)?'#bad4c5':pattern.palette[n].hex;ctx.fillRect(i%pattern.width,Math.floor(i/pattern.width),1,1);});return c;},[pattern,done,color]);
 useEffect(()=>{if(!size.width||!size.height)return;const c=canvas.current!,dpr=Math.min(devicePixelRatio||1,2);c.width=Math.round(size.width*dpr);c.height=Math.round(size.height*dpr);const ctx=c.getContext('2d')!;ctx.scale(dpr,dpr);ctx.fillStyle='#e9edf2';ctx.fillRect(0,0,size.width,size.height);
 const scale=view.scale,ox=size.width/2-view.cx*scale,oy=size.height/2-view.cy*scale;ctx.imageSmoothingEnabled=false;ctx.drawImage(raster,ox,oy,pattern.width*scale,pattern.height*scale);
 const x0=Math.max(0,Math.floor(-ox/scale)),x1=Math.min(pattern.width,Math.ceil((size.width-ox)/scale)),y0=Math.max(0,Math.floor(-oy/scale)),y1=Math.min(pattern.height,Math.ceil((size.height-oy)/scale));
 if(scale>=6){ctx.lineWidth=.6;ctx.strokeStyle='#54657455';ctx.beginPath();for(let x=x0;x<=x1;x++){ctx.moveTo(ox+x*scale,oy+y0*scale);ctx.lineTo(ox+x*scale,oy+y1*scale);}for(let y=y0;y<=y1;y++){ctx.moveTo(ox+x0*scale,oy+y*scale);ctx.lineTo(ox+x1*scale,oy+y*scale);}ctx.stroke();}
 for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const i=y*pattern.width+x,n=pattern.cells[i];if(n<0)continue;const px=ox+x*scale,py=oy+y*scale;
 if(done.has(i)&&scale>=12){ctx.strokeStyle='#49735c';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(px+2,py+scale*.6);ctx.lineTo(px+scale*.6,py+2);ctx.stroke();ctx.fillStyle='#355d49';ctx.font=`bold ${Math.max(9,scale*.23)}px sans-serif`;ctx.fillText('✓',px+scale*.63,py+scale*.3);}
 if(scale>=26){const bead=pattern.palette[n],[r,g,b]=rgb(bead.hex);ctx.fillStyle=done.has(i)?'#355d49':color!==null&&color!==n?'#727b83':r*.299+g*.587+b*.114<155?'#fff':'#222936';ctx.font=`${scale*(bead.code.length>4?.22:.3)}px monospace`;ctx.textAlign='center';ctx.fillText(bead.code,px+scale/2,py+scale*(done.has(i)?.78:.62));ctx.textAlign='start';}}
 ctx.strokeStyle='#b85b36';ctx.lineWidth=2;ctx.setLineDash([6,4]);ctx.strokeRect(ox+region.x*scale,oy+region.y*scale,region.width*scale,region.height*scale);ctx.setLineDash([]);
 if(selected!==null){const x=selected%pattern.width,y=Math.floor(selected/pattern.width);ctx.fillStyle='#b85b3620';ctx.fillRect(ox,oy+y*scale,pattern.width*scale,scale);ctx.fillRect(ox+x*scale,oy,scale,pattern.height*scale);ctx.strokeRect(ox+x*scale,oy+y*scale,scale,scale);}
 },[size,view,raster,pattern,done,region,color,selected]);
 useEffect(()=>{const node=canvas.current!,points=new Map<number,{x:number;y:number}>();let previous:{x:number;y:number;distance:number}|null=null,moved=false,start={x:0,y:0},multiple=false;let wheelTimer:ReturnType<typeof setTimeout>;
 const point=(e:PointerEvent)=>{const r=node.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};};
 const contact=()=>{const [a,b]=[...points.values()];return b?{x:(a.x+b.x)/2,y:(a.y+b.y)/2,distance:Math.hypot(a.x-b.x,a.y-b.y)}:{...a,distance:0};};
 const down=(e:PointerEvent)=>{node.setPointerCapture(e.pointerId);points.set(e.pointerId,point(e));previous=contact();if(points.size===1){start=point(e);moved=false;multiple=false;}else{multiple=true;moved=true;}};
 const move=(e:PointerEvent)=>{if(!points.has(e.pointerId))return;points.set(e.pointerId,point(e));const now=contact(),l=live.current;if(previous&&!l.props.locked){const dx=now.x-previous.x,dy=now.y-previous.y;if(Math.hypot(now.x-start.x,now.y-start.y)>4||multiple)moved=true;if(moved){const zoomed=now.distance&&previous.distance?zoomAt(l.view,now.distance/previous.distance,previous,l.size):l.view;change({...zoomed,cx:zoomed.cx-dx/zoomed.scale,cy:zoomed.cy-dy/zoomed.scale});}}previous=now;};
 const up=(e:PointerEvent)=>{if(!points.has(e.pointerId))return;points.delete(e.pointerId);if(!points.size){if(!moved&&!multiple&&e.type!=='pointercancel'){const l=live.current,i=cellAt(point(e),l.view,l.size,l.props.pattern);if(i!==null)l.props.onCell(i);}else if(!live.current.props.locked)live.current.props.onView(live.current.view);previous=null;}else previous=contact();};
 const wheel=(e:WheelEvent)=>{e.preventDefault();const l=live.current;if(l.props.locked)return;const r=node.getBoundingClientRect();change(zoomAt(l.view,Math.exp(-e.deltaY*.002),{x:e.clientX-r.left,y:e.clientY-r.top},l.size));clearTimeout(wheelTimer);wheelTimer=setTimeout(()=>live.current.props.onView(live.current.view),200);};
 node.addEventListener('pointerdown',down);node.addEventListener('pointermove',move);node.addEventListener('pointerup',up);node.addEventListener('pointercancel',up);node.addEventListener('wheel',wheel,{passive:false});return()=>{clearTimeout(wheelTimer);node.removeEventListener('pointerdown',down);node.removeEventListener('pointermove',move);node.removeEventListener('pointerup',up);node.removeEventListener('pointercancel',up);node.removeEventListener('wheel',wheel);};},[]);
 const zoom=(factor:number)=>change(zoomAt(view,factor,{x:size.width/2,y:size.height/2},size),true);
 return <div ref={host} style={{position:'relative',flex:1,minHeight:150,overflow:'hidden',background:'#e9edf2'}}><canvas ref={canvas} aria-label={`拼豆图纸画布，${pattern.width} 列、${pattern.height} 行`} role="img" style={{position:'absolute',width:'100%',height:'100%',touchAction:'none'}}/><View style={{position:'absolute',right:12,top:12,backgroundColor:'#fffffff2',borderRadius:24}}><IconButton icon="plus" label="放大图纸" disabled={locked} onPress={()=>zoom(1.5)}/><IconButton icon="minus" label="缩小图纸" disabled={locked} onPress={()=>zoom(1/1.5)}/><IconButton icon="fit" label="查看全图" disabled={locked} onPress={()=>change(fitRegion({x:0,y:0,width:pattern.width,height:pattern.height},size),true)}/><IconButton icon="target" label="定位当前区域" disabled={locked} onPress={()=>change(fitRegion(region,size),true)}/><IconButton icon={locked?'lock':'unlock'} label={locked?'解锁视图':'锁定视图'} onPress={props.onLock}/></View>{completed.length>0&&<Text style={{position:'absolute',top:12,left:10,color:'#355d49',backgroundColor:'#edf5ef',padding:8,borderRadius:8}}>✓ 已完成 · {completed.length} 格</Text>}<Text style={{position:'absolute',bottom:9,left:10,fontSize:10,padding:7,borderRadius:8,backgroundColor:'#fffffff0',color:'#606b79'}}>{locked?'视图已锁定':view.scale<26?'双指或滚轮放大查看色号':'轻点格子查看位置'} · {Math.round(view.scale*10)/10} px / 格</Text></div>;
});
