import assert from 'node:assert/strict';
import {mkdir,readFile} from 'node:fs/promises';
const engines=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await engines[process.env.BROWSER_ENGINE||'chromium'].launch({...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{}),headless:true});
const context=await browser.newContext({viewport:{width:393,height:852},deviceScaleFactor:2,isMobile:true,hasTouch:true,acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const url=process.env.TEST_URL||'http://localhost:5173';await mkdir('work',{recursive:true});
const click=async(name)=>page.getByRole(['制作','图纸','色卡','我的'].includes(name)?'tab':'button',{name,exact:true}).click();
try{
await page.goto(url);await page.getByRole('button',{name:'使用围巾小猫示例'}).waitFor();await click('使用围巾小猫示例');await click('下一步 · 选色卡');assert(await page.getByText('还没有色卡',{exact:true}).isVisible());await click('添加色卡');await click('品牌预设');await page.getByRole('textbox',{name:'搜索预设色卡'}).fill('咪小窝');await page.getByRole('button',{name:/^查看咪小窝.*286 色$/}).click();await click('添加并使用');await click('下一步 · 定尺寸');await click('自定义画布');await page.getByRole('textbox',{name:'画布宽度'}).fill('128');await page.getByRole('textbox',{name:'画布高度'}).fill('96');await click('应用尺寸');await page.getByText(/128 × 96 格 ·/).waitFor();await page.screenshot({path:'work/dimensions.png'});await click('下一步 · 看预览');await click('创建图纸');await page.getByRole('img',{name:'拼豆图纸画布，128 列、96 行'}).waitFor();await click('放大图纸');await click('定位当前区域');if(await page.getByRole('button',{name:'本区完成 · 下一待拼区域',exact:true}).count())await click('本区完成 · 下一待拼区域');await click('选择本区颜色');await page.getByRole('button',{name:/选择 .+，本区剩余 [1-9]/}).first().click();await page.getByRole('button',{name:/^完成本区 /}).click();await page.getByText(/✓ 已完成 ·/).waitFor();const progress=await page.getByText(/✓ 已完成 ·/).innerText();await page.waitForTimeout(400);await page.screenshot({path:'work/detail.png'});console.log('progress',progress);
await click('图纸更多操作');await click('导出图纸');const downloadEvent=page.waitForEvent('download');await click('SVG 高清图纸 · 完整色号');const download=await downloadEvent;await download.saveAs('work/chart.svg');assert((await readFile('work/chart.svg','utf8')).includes('<svg'));
await click('返回图纸列表');await page.reload();await click('图纸');await page.getByRole('button',{name:/^打开图纸 围巾小猫/}).click();assert.equal(await page.getByText(/✓ 已完成 ·/).innerText(),progress);
await click('撤销完成标记');await page.getByText(/✓ 已完成 ·/).waitFor({state:'hidden'});await click('返回图纸列表');await click('我的');await page.getByText('离线资源已就绪，可从主屏幕继续使用。',{exact:true}).waitFor();const backupEvent=page.waitForEvent('download');await click('导出全部图纸备份');await(await backupEvent).saveAs('work/backup.json');if(process.env.TEST_OFFLINE!=='0')await context.setOffline(true);await page.reload();await page.getByRole('button',{name:'使用围巾小猫示例'}).waitFor();await click('图纸');await page.getByRole('button',{name:/^打开图纸 围巾小猫/}).click();await page.getByRole('img',{name:'拼豆图纸画布，128 列、96 行'}).waitFor();await context.setOffline(false);
await click('查看全图');await page.waitForTimeout(150);const chart=page.getByRole('img',{name:'拼豆图纸画布，128 列、96 行'});const bounds=await chart.boundingBox();const center={x:bounds.x+bounds.width*.45,y:bounds.y+bounds.height*.5};await page.mouse.move(center.x,center.y);await page.mouse.down();await page.mouse.move(center.x+35,center.y+20,{steps:8});await page.mouse.up();await page.waitForTimeout(100);await page.mouse.click(center.x,center.y);await page.getByText(/行 \d+ · 列 \d+/).waitFor();if((process.env.BROWSER_ENGINE||'chromium')==='chromium'){const cdp=await context.newCDPSession(page);const readout=()=>page.getByText(/px \/ 格/).innerText();const before=await readout();const y=center.y;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:100,y,id:1},{x:200,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:70,y,id:1},{x:230,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notEqual(await readout(),before);await cdp.detach();}await click('锁定视图');await page.getByText(/视图已锁定/).waitFor();await click('解锁视图');
await click('返回图纸列表');await click('删除图纸 围巾小猫');await click('移至最近删除');await click('查看最近删除');await click('恢复 围巾小猫');await click('返回全部图纸');await page.getByRole('button',{name:/^打开图纸 围巾小猫/}).waitFor();
await click('我的');await page.locator('input[type=file]').setInputFiles('work/backup.json');await page.getByText('已导入 0 张图纸，已有图纸已跳过。',{exact:true}).waitFor();
await click('制作');await click('使用围巾小猫示例');await click('下一步 · 选色卡');await page.getByRole('button',{name:/^使用咪小窝/}).click();await click('下一步 · 定尺寸');await click('自定义画布');await page.getByRole('textbox',{name:'画布宽度'}).fill('513');assert.equal(await page.getByRole('button',{name:'应用尺寸',exact:true}).getAttribute('aria-disabled'),'true');await page.getByRole('textbox',{name:'画布宽度'}).fill('512');await page.getByRole('textbox',{name:'画布高度'}).fill('512');await click('应用尺寸');await page.getByText(/512 × 512 格 ·/).waitFor();await click('下一步 · 看预览');await click('创建图纸');await page.getByRole('img',{name:'拼豆图纸画布，512 列、512 行'}).waitFor();await click('查看全图');await page.waitForTimeout(400);await page.screenshot({path:'work/large-chart.png'});await click('放大图纸');await click('定位当前区域');
const workerFile=JSON.parse(await readFile('src/web/build-info.json','utf8')).worker;const performance=await page.evaluate(async workerFile=>{const worker=new Worker(workerFile);const raster={width:256,height:256,data:new Uint8ClampedArray(256*256*4)};for(let i=0;i<256*256;i++)raster.data.set([i%256,(i*7)%256,(i*19)%256,255],i*4);const colors=Array.from({length:291},(_,i)=>({code:`A${i}`,name:`A${i}`,hex:'#'+((i*57347)%16777216).toString(16).padStart(6,'0')}));let ticks=0;const timer=setInterval(()=>ticks++,10),start=performance.now();const result=await new Promise((resolve,reject)=>{worker.onmessage=e=>e.data.error?reject(Error(e.data.error)):resolve(e.data.result);worker.onerror=reject;worker.postMessage({method:'generate',payload:{raster,card:{colors},options:{width:512,height:512,maxColors:512,fit:'cover',dithering:false,cleanup:false,removeBackground:false}}});});clearInterval(timer);worker.terminate();return{ms:Math.round(performance.now()-start),ticks,total:result.total};},workerFile);assert.equal(performance.total,262144);assert(performance.ticks>0);console.log('512 benchmark',performance);assert.deepEqual(errors,[]);console.log(`offline simulation: ${process.env.TEST_OFFLINE==='0'?'SKIPPED (explicit TEST_OFFLINE=0)':'passed'}`);console.log('PASS mobile creation, preset search, exact canvas, progress reload/undo, SVG, backup/import, gestures, delete/restore and 512 Worker');
}catch(e){console.log('FAILED SCREEN',await page.locator('body').innerText());await page.screenshot({path:'work/failure.png'});throw e;}finally{await browser.close();}
