import {useEffect,useRef,useState} from 'react';
import {Text,View} from 'react-native';
import {Button,Notice,ui} from '../components/UI';
import {saveFile} from '../lib/files.web';
import type {Project} from '../lib/projects';
import {parseBackup} from './backup';
export function WebSettings({projects,onImport}:{projects:Project[];onImport:(projects:Project[])=>Promise<boolean>}){
 const input=useRef<HTMLInputElement>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[offline,setOffline]=useState(false),[update,setUpdate]=useState(false);
 useEffect(()=>{const sync=()=>{setOffline(!!navigator.serviceWorker?.controller);void navigator.serviceWorker?.getRegistration().then(r=>setUpdate(!!r?.waiting));};sync();navigator.serviceWorker?.addEventListener('controllerchange',sync);window.addEventListener('bead-update',sync);return()=>{navigator.serviceWorker?.removeEventListener('controllerchange',sync);window.removeEventListener('bead-update',sync);};},[]);
 return <View style={[ui.card,{gap:14,marginTop:16}]}><Text style={ui.label}>数据与安装</Text><Button label="导出全部图纸备份" disabled={busy||!projects.length} onPress={()=>void saveFile(JSON.stringify({schemaVersion:1,projects}),`bead-backup-${new Date().toISOString().slice(0,10)}.json`,'application/json')}/><Button label={busy?'正在导入…':'导入图纸或备份'} disabled={busy} onPress={()=>input.current?.click()}/><input ref={input} type="file" accept=".json,application/json" style={{display:'none'}} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);try{if(file.size>80*1024*1024)throw new Error('备份文件不能超过 80 MB。');const incoming=parseBackup(await file.text());const added=incoming.filter(p=>!projects.some(old=>old.id===p.id)).length;if(await onImport(incoming))setMessage(`已导入 ${added} 张图纸，已有图纸已跳过。`);}catch(e){setMessage(e instanceof Error?e.message:'导入失败，请检查文件。');}finally{setBusy(false);}}}/><Text style={ui.note}>备份包含图纸、用色信息和拼制进度。独立创建但未用于图纸的色卡暂不包含在此备份中。</Text><Text style={ui.label}>添加到 iPhone 主屏幕</Text><Text style={ui.text}>使用 Safari 打开网页，轻点分享按钮，选择「添加到主屏幕」，开启「作为网页 App 打开」，再点「添加」。</Text><Notice text={offline?'离线资源已就绪，可从主屏幕继续使用。':isSecureContext?'首次联网加载后将准备离线资源。':'当前是局域网 HTTP 预览。正式使用主屏幕 App 和离线功能，需要部署到 HTTPS 地址。'}/>{update&&<Button label="更新应用并重新载入" onPress={async()=>{const r=await navigator.serviceWorker.getRegistration();if(r?.waiting){window.dispatchEvent(new Event('bead-apply-update'));r.waiting.postMessage({type:'ACTIVATE'});}}}/>}{message&&<Notice text={message}/>}</View>;
}
